package main.view;

public enum RiskEventType {
    UPDATE_MAP,
    GAME_BEGAN,
    DIE_ROLLED,
    RESTORE_GUI,
    UPDATE_ATTACKABLE,
    ATTACK_COMMENCED,
    ATTACK_COMPLETED,
    TERRITORY_DOMINATED,
    TERRITORY_DEFENDED,
    UNITS_MOVED,
    TURN_BEGAN,
    TURN_ENDED,
    GAME_OVER
}
